### ISSUE TITLE
Win7 problem + fix

### ISSUE THREAD

**Issue by rwbc** [mhonert/chess#1]
Hi Martin,

Today I found your Wasabi engine announced in the public CCRL forum and as I am the maintainer
of the XB/UCI chronology I wanted to check it before adding it to the chronology.
https://rwbc-chess.de/
https://docs.google.com/spreadsheets/d/1GXoy3lGhdKPJbatdw2_2dhWT3TkpthPcNtHs51MQydM/edit#gid=175552346

Wasm gives me an error on my old Win7-64 machine.
`The procedure entry point GetSystemTimePreciseAsFileTime could not be located in the dynamic link library KERNEL32.dll.`
Some googling led to attempting me to install a certain KB file from MS, but it couldn't be installed here. (KB2533623)

Another try was successful though and I just replaced Wasm with Wasmer and linked against it.
https://github.com/wasmerio/wasmer/releases
May be this helps people with the same problem. (still a lot Win7 users in the computerchess scene)

```
0.000: - Starting server: C:\Program Files (x86)\Wasmer\bin\wasmer.exe run C:\Engines\UCI\Wasabi_121-64\engine.wasm
0.046: - Priority class set to normal
0.046: - Thread priority set to normal
2.074: < Wasabi 1.2.1 by mhonert
3.775: > uci
3.775: < id name Wasabi 1.2.1
3.775: < id author mhonert
3.775: < option name Hash type spin default 32 min 1 max 768
3.775: < option name OwnBook type check default false
3.775: < option name UCI_EngineAbout type string default Wasabi Chess Engine (https://github.com/mhonert/chess)
3.775: < uciok
```

Do you have an idea of the speed difference with Wasmer vs. Wasm?

Guenther (RWBC)

**Comment by mhonert** [comment]
Hi Guenther,

thanks for trying out my chess engine and for providing the Win7 fix!
It seems that the earliest version which supports GetSystemTimePreciseAsFileTime is Windows 8.

I benchmarked several WebAssembly runtimes and WAVM was the fastest.
With the default backend, Wasmer is around 4 times slower than WAVM.
By using the ```--backend llvm``` option with Wasmer, performances increases, but is still around 30% slower than WAVM.
I'm not sure how many ELO points this translates to.

But for Windows 7 users the best option right now is to use Wasmer with the "--backend llvm" line, e.g.
```wasmer.exe run --backend llvm engine.wasm```

For the next release I will add a note for Windows 7 users to the release page.

Best regards,
Martin

**Comment by rwbc** [comment]
Martin, thanks for the quick answer and for the backend speedup hint :)

**Comment by mhonert** [comment]
The workaround is now documented in the [Wiki](https://github.com/mhonert/chess/wiki/Windows-7) and the release page contains a note for Windows 7 users, which links to the Wiki.

If the performance difference between WAVM and Wasmer becomes smaller in the future, I will probably switch out the bundled runtime.
